// <auto-generated />
using System;
using CodeFirstApi.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace CodeFirstApi.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20220108222246_UpdateManager")]
    partial class UpdateManager
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.2");

            modelBuilder.Entity("CodeFirstApi.Entities.DcClass", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<int?>("DcFrameId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Occupation")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DcFrameId");

                    b.ToTable("DcClases");
                });

            modelBuilder.Entity("CodeFirstApi.Entities.DcFrame", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<int?>("DcManagerId")
                        .HasColumnType("int");

                    b.Property<int>("FrameCode")
                        .HasColumnType("int");

                    b.Property<string>("FrameName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("DcManagerId");

                    b.ToTable("DcFrames");
                });

            modelBuilder.Entity("CodeFirstApi.Entities.DcManager", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("DcManagers");
                });

            modelBuilder.Entity("CodeFirstApi.Entities.DcClass", b =>
                {
                    b.HasOne("CodeFirstApi.Entities.DcFrame", "DcFrame")
                        .WithMany("Classes")
                        .HasForeignKey("DcFrameId");

                    b.Navigation("DcFrame");
                });

            modelBuilder.Entity("CodeFirstApi.Entities.DcFrame", b =>
                {
                    b.HasOne("CodeFirstApi.Entities.DcManager", "DcManager")
                        .WithMany()
                        .HasForeignKey("DcManagerId");

                    b.Navigation("DcManager");
                });

            modelBuilder.Entity("CodeFirstApi.Entities.DcFrame", b =>
                {
                    b.Navigation("Classes");
                });
#pragma warning restore 612, 618
        }
    }
}
